language: scala
jdk:
  - openjdk6
scala:
  - 2.11.5
#  - 2.10.4
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  # coverage only for unit tests, not integration tests
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile doc &&
    ./.check-diff.sh &&
    sbt ++$TRAVIS_SCALA_VERSION test
    #&& sbt ++$TRAVIS_SCALA_VERSION clean coverage test
#after_success:
#  - sbt ++$TRAVIS_SCALA_VERSION coveralls
