language: scala
jdk:
  - openjdk7
scala:
  - 2.11.7

sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
env:
  global:
    - AKKA_TEST_TIMEFACTOR=10
script:
  # coverage only for unit tests, not integration tests
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile doc &&
    ./.check-diff.sh &&
    sbt ++$TRAVIS_SCALA_VERSION test
    #&& sbt ++$TRAVIS_SCALA_VERSION clean coverage test
#after_success:
#  - sbt ++$TRAVIS_SCALA_VERSION coveralls
